name: Build

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Build Deno Windows
        run: |
          cd deno
          deno compile -A --target x86_64-pc-windows-msvc --output nico-renamer-deno ./main.ts

      - name: Build Deno MacOS
        run: |
          cd deno
          deno compile -A --target x86_64-apple-darwin --output nico-renamer-deno ./main.ts

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build Bun Windows
        run: |
          cd node
          bun install
          bun build --compile --minify --bytecode --format esm --target=bun-windows-x64-modern --outfile nico-renamer-bun ./index.ts

      - name: Build Bun MacOS
        run: |
          cd node
          bun install
          bun build --compile --minify --bytecode --format esm --target=bun-darwin-arm64 --outfile nico-renamer-bun ./index.ts

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
          use-cache: false

      - name: Build Zig Windows
        run: |
          cd zig
          zig build --release=safe -Dtarget=x86_64-windows

      - name: Build Zig MacOS
        run: |
          cd zig
          zig build --release=safe -Dtarget=x86_64-macos

      - name: Get current date
        id: date
        run: |
          echo "builddate=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: nightly-${{ env.builddate }}
          tag_name: nightly-${{ env.builddate }}
          files: |
            deno/nico-renamer-deno.exe
            deno/nico-renamer-deno
            node/nico-renamer-bun.exe
            node/nico-renamer-bun
            zig/zig-out/bin/nico-renamer-zig.exe
            zig/zig-out/bin/nico-renamer-zig
